name: deploy-systemd
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ssh scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.DC_HOST }}
        user: ${{ secrets.DC_USER }}
        key: ${{ secrets.DC_KEY }}
        port: ${{ secrets.DC_PORT }}
        connect_timeout: 10s
        scp: |
          './*' => /etc/overheard_at_shad/overheard-at-shad/
        last_ssh: |
          echo "Restarting service..." && 
          systemctl restart overheard-at-shad.service &&
          systemctl status overheard-at-shad.service &&
          echo "Done"
